# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PCA',
                'doc_host': 'https://Maryam-Sargol.github.io',
                'git_url': 'https://github.com/Maryam-Sargol/PCA',
                'lib_path': 'PCA'},
  'syms': {'PCA.start': {'PCA.start.foo': ('start.html#foo', 'PCA/start.py')}}}
