# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PCA',
                'doc_host': 'https://Maryam-Sargol.github.io',
                'git_url': 'https://github.com/Maryam-Sargol/PCA',
                'lib_path': 'PCA'},
  'syms': { 'PCA.STD': {'PCA.STD.desired_STD': ('std.html#desired_std', 'PCA/STD.py')},
            'PCA.example_jupyter': {},
            'PCA.export_file_mix': {'PCA.export_file_mix.export_file': ('export_file_mix.html#export_file', 'PCA/export_file_mix.py')},
            'PCA.export_key': {'PCA.export_key.export_key_file': ('export_key.html#export_key_file', 'PCA/export_key.py')},
            'PCA.extract_NSH_stl_key': { 'PCA.extract_NSH_stl_key.extract_nodes_shells_mix_stl_key': ( 'extract_nsh_stl_key.html#extract_nodes_shells_mix_stl_key',
                                                                                                       'PCA/extract_NSH_stl_key.py')},
            'PCA.main_pca': {},
            'PCA.pca': {'PCA.pca.run_PCA': ('pca.html#run_pca', 'PCA/pca.py')},
            'PCA.read_extract': { 'PCA.read_extract.read_extract_nodes_shells': ( 'read_extract.html#read_extract_nodes_shells',
                                                                                  'PCA/read_extract.py')}}}
